video_stream_homepage:
    path:     /
    defaults: { _controller: videoStreamBundle:Home:index }

# REGISTRATION
&:
    pattern: /register
    defaults: { _controller: videoStreamBundle:Home:register }
    requirements:
        _method: GET|POST

# Page view video
stream_view_video:
    pattern: /view/{video_id}
    defaults: { _controller: videoStreamBundle:Home:view }
    requirements:
        _method: GET

# UPLOAD
upload_video:
    pattern: /upload
    defaults: { _controller: videoStreamBundle:Home:upload }
    requirements:
        _method: GET|POST